# Generated by Django 5.2.5 on 2025-09-08 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('python_fullstack', 'Python Full Stack'), ('ml_ai', 'ML / AI'), ('java_fullstack', 'Java Full Stack')], max_length=30, unique=True)),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Course Track',
                'verbose_name_plural': 'Course Tracks',
            },
        ),
        migrations.CreateModel(
            name='CourseModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.coursetrack')),
            ],
            options={
                'verbose_name': 'Course Module',
                'verbose_name_plural': 'Course Modules',
                'ordering': ['track', 'order'],
            },
        ),
    ]
