# Generated by Django 5.2.5 on 2025-09-15 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subject',
            new_name='Course',
        ),
        migrations.RenameField(
            model_name='mark',
            old_name='subject',
            new_name='course',
        ),
        migrations.AlterUniqueTogether(
            name='mark',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='mark',
            constraint=models.UniqueConstraint(fields=('student', 'course'), name='student_course_marks'),
        ),
    ]
