# Generated by Django 5.1.2 on 2025-09-22 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_coursemodule_order_student_enrollment'),
        ('mentor', '0003_alter_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.coursetrack'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='courses.coursetrack'),
        ),
    ]
