# Generated by Django 5.1.2 on 2025-09-25 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_student_user_course_delete_enrollment_and_more'),
        ('mentor', '0004_course_track_alter_mark_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='courses.course'),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
